# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-06-23 09:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Query2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Staffregistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('staffid', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('faculty', models.CharField(max_length=255)),
                ('college', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=255)),
                ('course', models.CharField(max_length=255)),
                ('emailid', models.CharField(max_length=255)),
                ('dob', models.CharField(max_length=255)),
                ('mobileno', models.CharField(max_length=255)),
                ('image', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Studentregistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('studentid', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('faculty', models.CharField(max_length=255)),
                ('college', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=255)),
                ('course', models.CharField(max_length=255)),
                ('semester', models.CharField(max_length=255)),
                ('emailid', models.CharField(max_length=255)),
                ('dob', models.CharField(max_length=255)),
                ('mobileno', models.CharField(max_length=255)),
                ('image', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='query2',
            name='studentregistration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Studentregistration'),
        ),
        migrations.AddField(
            model_name='query',
            name='staffregistration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Staffregistration'),
        ),
    ]
